baseURL = "sazzad.info"
languageCode = "en-us"
title = "Hugo Serial Programmer"
rssLimit = 20
copyright = "2024 0xSAZZAD | All rights reserved"
minify = false

[Author]
  name = "0xSAZZAD"
  email = "swe.sazzad@gmail.com"

[permalinks]
  posts = "/:year/:month/:day/:filename"
  pages = "/:slug"

[taxonomies]
  tag = "tags"
  category = "categories"

[outputs]
  home = ["html", "json", "rss"]